services:
  frontend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 3000:3000

    environment:
      - MONGODB_URI=mongodb://db:27017/bambuApp

    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: .
          target: /app
          action: sync
    volumes:
      - uploads:/app/public/uploads

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - database:/data/db

volumes:
  database:
  uploads:
