import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="flex">
          <div className="hidden h-[100vh] w-[300px] p-3 md:block">
            <Sidebar />
          </div>
          <div className="w-full p-5 md:max-w-[1140px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
